services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  bluesky-firehose-classifier:
    build:
      context: .       
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3000:3000"
    profiles: ["default"]
  text-category-classifier:
    build:
      context: ./python/text-category-classifier  
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3101:3101"
    profiles: ["text-category-classifier"]
  text-finsentiment-classifier:
    build:
      context: ./python/text-finsentiment-classifier
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3100:3100"    
    profiles: ["text-fin-sentiment-classifier"]