services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    profiles: ["default", "mongo"]
  bluesky-firehose-classifier:
    container_name: bluesky-firehose-classifier
    build:
      context: .       
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3000:3000"
    profiles: ["default"]
    depends_on:
      - text-category-classifier
      - text-finsentiment-classifier
  text-category-classifier:
    container_name: text-category-classifier
    build:
      context: ./python/text-category-classifier  
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3101:3101"
    profiles: ["default", "text-category-classifier"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3101/livez"]
      interval: 10s
      timeout: 5s
      retries: 3
  text-finsentiment-classifier:
    container_name: text-finsentiment-classifier
    build:
      context: ./python/text-finsentiment-classifier
      dockerfile: Dockerfile 
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "3100:3100"    
    profiles: ["default", "text-fin-sentiment-classifier"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/livez"]
      interval: 10s
      timeout: 5s
      retries: 3