// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/models/message.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Values        []*Value               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_internal_models_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Label) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_internal_models_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Value) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Index         *Index                 `protobuf:"bytes,2,opt,name=index,proto3,oneof" json:"index,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_internal_models_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Entity) GetIndex() *Index {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *Entity) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Identity
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_internal_models_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Identity) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Identity) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Identity) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

// Facet
type Facet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Features      []*Feature             `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	Index         *Index                 `protobuf:"bytes,3,opt,name=index,proto3,oneof" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_internal_models_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{4}
}

func (x *Facet) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Facet) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Facet) GetIndex() *Index {
	if x != nil {
		return x.Index
	}
	return nil
}

// Feature
type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Link          *Link                  `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Uri           *string                `protobuf:"bytes,3,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	Tag           *string                `protobuf:"bytes,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Did           *string                `protobuf:"bytes,5,opt,name=did,proto3,oneof" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_internal_models_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{5}
}

func (x *Feature) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Feature) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *Feature) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *Feature) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *Feature) GetDid() string {
	if x != nil && x.Did != nil {
		return *x.Did
	}
	return ""
}

// Link
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_internal_models_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{6}
}

func (x *Link) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// Index
type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	ByteStart     int32                  `protobuf:"varint,2,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	ByteEnd       int32                  `protobuf:"varint,3,opt,name=byte_end,json=byteEnd,proto3" json:"byte_end,omitempty"`
	End           *int32                 `protobuf:"varint,4,opt,name=end,proto3,oneof" json:"end,omitempty"`
	Start         *int32                 `protobuf:"varint,5,opt,name=start,proto3,oneof" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_internal_models_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{7}
}

func (x *Index) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Index) GetByteStart() int32 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *Index) GetByteEnd() int32 {
	if x != nil {
		return x.ByteEnd
	}
	return 0
}

func (x *Index) GetEnd() int32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *Index) GetStart() int32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

// Embed
type Embed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,json=$type,proto3" json:"type,omitempty"`
	Images        []*EmbedImage          `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	External      *EmbedExternal         `protobuf:"bytes,3,opt,name=external,proto3,oneof" json:"external,omitempty"`
	Media         *EmbedMedia            `protobuf:"bytes,4,opt,name=media,proto3,oneof" json:"media,omitempty"`
	Video         *EmbedVideo            `protobuf:"bytes,5,opt,name=video,proto3,oneof" json:"video,omitempty"`
	AspectRatio   *AspectRatio           `protobuf:"bytes,6,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Record        *EmbedRecord           `protobuf:"bytes,7,opt,name=record,proto3,oneof" json:"record,omitempty"`
	Alt           *string                `protobuf:"bytes,8,opt,name=alt,proto3,oneof" json:"alt,omitempty"`
	Alttext       *string                `protobuf:"bytes,9,opt,name=alttext,proto3,oneof" json:"alttext,omitempty"`
	Captions      *string                `protobuf:"bytes,10,opt,name=captions,proto3,oneof" json:"captions,omitempty"`
	Data          map[string]string      `protobuf:"bytes,11,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uri           *string                `protobuf:"bytes,12,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embed) Reset() {
	*x = Embed{}
	mi := &file_internal_models_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embed) ProtoMessage() {}

func (x *Embed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embed.ProtoReflect.Descriptor instead.
func (*Embed) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{8}
}

func (x *Embed) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Embed) GetImages() []*EmbedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Embed) GetExternal() *EmbedExternal {
	if x != nil {
		return x.External
	}
	return nil
}

func (x *Embed) GetMedia() *EmbedMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Embed) GetVideo() *EmbedVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *Embed) GetAspectRatio() *AspectRatio {
	if x != nil {
		return x.AspectRatio
	}
	return nil
}

func (x *Embed) GetRecord() *EmbedRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Embed) GetAlt() string {
	if x != nil && x.Alt != nil {
		return *x.Alt
	}
	return ""
}

func (x *Embed) GetAlttext() string {
	if x != nil && x.Alttext != nil {
		return *x.Alttext
	}
	return ""
}

func (x *Embed) GetCaptions() string {
	if x != nil && x.Captions != nil {
		return *x.Captions
	}
	return ""
}

func (x *Embed) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Embed) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

// EmbedVideo
type EmbedVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Ref           *Blob                  `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	MimeType      *string                `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Size          *int32                 `protobuf:"varint,4,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedVideo) Reset() {
	*x = EmbedVideo{}
	mi := &file_internal_models_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedVideo) ProtoMessage() {}

func (x *EmbedVideo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedVideo.ProtoReflect.Descriptor instead.
func (*EmbedVideo) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedVideo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedVideo) GetRef() *Blob {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *EmbedVideo) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *EmbedVideo) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

// EmbedRecord
type EmbedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Cid           *string                `protobuf:"bytes,2,opt,name=cid,proto3,oneof" json:"cid,omitempty"`
	Uri           *string                `protobuf:"bytes,3,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	Record        *Record                `protobuf:"bytes,4,opt,name=record,proto3,oneof" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRecord) Reset() {
	*x = EmbedRecord{}
	mi := &file_internal_models_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRecord) ProtoMessage() {}

func (x *EmbedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRecord.ProtoReflect.Descriptor instead.
func (*EmbedRecord) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{10}
}

func (x *EmbedRecord) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedRecord) GetCid() string {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return ""
}

func (x *EmbedRecord) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *EmbedRecord) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// EmbedMedia
type EmbedMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	External      *EmbedExternal         `protobuf:"bytes,2,opt,name=external,proto3,oneof" json:"external,omitempty"`
	Images        []*Image               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	AspectRatio   *AspectRatio           `protobuf:"bytes,4,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Video         *EmbedVideo            `protobuf:"bytes,5,opt,name=video,proto3,oneof" json:"video,omitempty"`
	Alt           *string                `protobuf:"bytes,6,opt,name=alt,proto3,oneof" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedMedia) Reset() {
	*x = EmbedMedia{}
	mi := &file_internal_models_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedMedia) ProtoMessage() {}

func (x *EmbedMedia) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedMedia.ProtoReflect.Descriptor instead.
func (*EmbedMedia) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{11}
}

func (x *EmbedMedia) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedMedia) GetExternal() *EmbedExternal {
	if x != nil {
		return x.External
	}
	return nil
}

func (x *EmbedMedia) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *EmbedMedia) GetAspectRatio() *AspectRatio {
	if x != nil {
		return x.AspectRatio
	}
	return nil
}

func (x *EmbedMedia) GetVideo() *EmbedVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *EmbedMedia) GetAlt() string {
	if x != nil && x.Alt != nil {
		return *x.Alt
	}
	return ""
}

// EmbedExternal
type EmbedExternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Thumb         *Image                 `protobuf:"bytes,3,opt,name=thumb,proto3,oneof" json:"thumb,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Uri           *string                `protobuf:"bytes,5,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedExternal) Reset() {
	*x = EmbedExternal{}
	mi := &file_internal_models_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedExternal) ProtoMessage() {}

func (x *EmbedExternal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedExternal.ProtoReflect.Descriptor instead.
func (*EmbedExternal) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{12}
}

func (x *EmbedExternal) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedExternal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EmbedExternal) GetThumb() *Image {
	if x != nil {
		return x.Thumb
	}
	return nil
}

func (x *EmbedExternal) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *EmbedExternal) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

type EmbedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Alt           *string                `protobuf:"bytes,2,opt,name=alt,proto3,oneof" json:"alt,omitempty"`
	Image         *Image                 `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	AspectRatio   *AspectRatio           `protobuf:"bytes,4,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Captions      *string                `protobuf:"bytes,5,opt,name=captions,proto3,oneof" json:"captions,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedImage) Reset() {
	*x = EmbedImage{}
	mi := &file_internal_models_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedImage) ProtoMessage() {}

func (x *EmbedImage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedImage.ProtoReflect.Descriptor instead.
func (*EmbedImage) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{13}
}

func (x *EmbedImage) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedImage) GetAlt() string {
	if x != nil && x.Alt != nil {
		return *x.Alt
	}
	return ""
}

func (x *EmbedImage) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *EmbedImage) GetAspectRatio() *AspectRatio {
	if x != nil {
		return x.AspectRatio
	}
	return nil
}

func (x *EmbedImage) GetCaptions() string {
	if x != nil && x.Captions != nil {
		return *x.Captions
	}
	return ""
}

func (x *EmbedImage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type AspectRatio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AspectRatio) Reset() {
	*x = AspectRatio{}
	mi := &file_internal_models_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AspectRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectRatio) ProtoMessage() {}

func (x *AspectRatio) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectRatio.ProtoReflect.Descriptor instead.
func (*AspectRatio) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{14}
}

func (x *AspectRatio) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AspectRatio) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AspectRatio) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Ref           *Blob                  `protobuf:"bytes,2,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	MimeType      *string                `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Size          *int32                 `protobuf:"varint,4,opt,name=size,proto3,oneof" json:"size,omitempty"`
	AspectRatio   *AspectRatio           `protobuf:"bytes,5,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Alt           *string                `protobuf:"bytes,6,opt,name=alt,proto3,oneof" json:"alt,omitempty"`
	Image         *Image                 `protobuf:"bytes,7,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Cid           *string                `protobuf:"bytes,8,opt,name=cid,proto3,oneof" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_internal_models_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{15}
}

func (x *Image) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Image) GetRef() *Blob {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Image) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *Image) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Image) GetAspectRatio() *AspectRatio {
	if x != nil {
		return x.AspectRatio
	}
	return nil
}

func (x *Image) GetAlt() string {
	if x != nil && x.Alt != nil {
		return *x.Alt
	}
	return ""
}

func (x *Image) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Image) GetCid() string {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return ""
}

type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *string                `protobuf:"bytes,1,opt,name=link,json=$link,proto3,oneof" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_internal_models_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{16}
}

func (x *Blob) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

type Ref struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Cid              *string                `protobuf:"bytes,2,opt,name=cid,proto3,oneof" json:"cid,omitempty"`
	Uri              *string                `protobuf:"bytes,3,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	Link             *string                `protobuf:"bytes,4,opt,name=link,json=$link,proto3,oneof" json:"link,omitempty"`
	Ref              *string                `protobuf:"bytes,5,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	ValidationStatus *string                `protobuf:"bytes,6,opt,name=validation_status,json=validationStatus,proto3,oneof" json:"validation_status,omitempty"`
	Commit           *Commit                `protobuf:"bytes,7,opt,name=commit,proto3,oneof" json:"commit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_internal_models_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{17}
}

func (x *Ref) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Ref) GetCid() string {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return ""
}

func (x *Ref) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *Ref) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *Ref) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

func (x *Ref) GetValidationStatus() string {
	if x != nil && x.ValidationStatus != nil {
		return *x.ValidationStatus
	}
	return ""
}

func (x *Ref) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,json=$type,proto3,oneof" json:"type,omitempty"`
	Parent        *Ref                   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Root          *Ref                   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_internal_models_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{18}
}

func (x *Reply) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Reply) GetParent() *Ref {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Reply) GetRoot() *Ref {
	if x != nil {
		return x.Root
	}
	return nil
}

type Record struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                string                 `protobuf:"bytes,1,opt,name=type,json=$type,proto3" json:"type,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Langs               []string               `protobuf:"bytes,3,rep,name=langs,proto3" json:"langs,omitempty"`
	Text                string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Embed               *Embed                 `protobuf:"bytes,5,opt,name=embed,proto3,oneof" json:"embed,omitempty"`
	Reply               *Reply                 `protobuf:"bytes,6,opt,name=reply,proto3,oneof" json:"reply,omitempty"`
	Facets              []*Facet               `protobuf:"bytes,7,rep,name=facets,proto3" json:"facets,omitempty"`
	Tags                []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Via                 *string                `protobuf:"bytes,9,opt,name=via,proto3,oneof" json:"via,omitempty"`
	Label               *string                `protobuf:"bytes,10,opt,name=label,proto3,oneof" json:"label,omitempty"`
	BridgyOriginalText  *string                `protobuf:"bytes,11,opt,name=bridgy_original_text,json=bridgyOriginalText,proto3,oneof" json:"bridgy_original_text,omitempty"`
	BridgyOriginalUrl   *string                `protobuf:"bytes,12,opt,name=bridgy_original_url,json=bridgyOriginalUrl,proto3,oneof" json:"bridgy_original_url,omitempty"`
	Actor               *string                `protobuf:"bytes,13,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	Size                *int32                 `protobuf:"varint,14,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Cid                 *string                `protobuf:"bytes,15,opt,name=cid,proto3,oneof" json:"cid,omitempty"`
	Uri                 *string                `protobuf:"bytes,16,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	Labels              *Label                 `protobuf:"bytes,17,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	Entities            []*Entity              `protobuf:"bytes,18,rep,name=entities,proto3" json:"entities,omitempty"`
	External            *EmbedExternal         `protobuf:"bytes,19,opt,name=external,proto3,oneof" json:"external,omitempty"`
	Lang                []string               `protobuf:"bytes,20,rep,name=lang,proto3" json:"lang,omitempty"` // alternate to langs
	Title               *string                `protobuf:"bytes,21,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Visibility          *string                `protobuf:"bytes,22,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	SpaceAoisoraPostVia *string                `protobuf:"bytes,23,opt,name=space_aoisora_post_via,json=space.aoisora.post.via,proto3,oneof" json:"space_aoisora_post_via,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_internal_models_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{19}
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Record) GetLangs() []string {
	if x != nil {
		return x.Langs
	}
	return nil
}

func (x *Record) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Record) GetEmbed() *Embed {
	if x != nil {
		return x.Embed
	}
	return nil
}

func (x *Record) GetReply() *Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *Record) GetFacets() []*Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *Record) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Record) GetVia() string {
	if x != nil && x.Via != nil {
		return *x.Via
	}
	return ""
}

func (x *Record) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Record) GetBridgyOriginalText() string {
	if x != nil && x.BridgyOriginalText != nil {
		return *x.BridgyOriginalText
	}
	return ""
}

func (x *Record) GetBridgyOriginalUrl() string {
	if x != nil && x.BridgyOriginalUrl != nil {
		return *x.BridgyOriginalUrl
	}
	return ""
}

func (x *Record) GetActor() string {
	if x != nil && x.Actor != nil {
		return *x.Actor
	}
	return ""
}

func (x *Record) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *Record) GetCid() string {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return ""
}

func (x *Record) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *Record) GetLabels() *Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Record) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Record) GetExternal() *EmbedExternal {
	if x != nil {
		return x.External
	}
	return nil
}

func (x *Record) GetLang() []string {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *Record) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Record) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *Record) GetSpaceAoisoraPostVia() string {
	if x != nil && x.SpaceAoisoraPostVia != nil {
		return *x.SpaceAoisoraPostVia
	}
	return ""
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           string                 `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Rkey          string                 `protobuf:"bytes,4,opt,name=rkey,proto3" json:"rkey,omitempty"`
	Record        *Record                `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`
	Cid           string                 `protobuf:"bytes,6,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_internal_models_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{20}
}

func (x *Commit) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *Commit) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Commit) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Commit) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *Commit) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Commit) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type ProtoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	TimeUs        int64                  `protobuf:"varint,2,opt,name=time_us,json=timeUs,proto3" json:"time_us,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Commit        *Commit                `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	FinSentiment  *string                `protobuf:"bytes,6,opt,name=fin_sentiment,json=finSentiment,proto3,oneof" json:"fin_sentiment,omitempty"`
	Account       *Account               `protobuf:"bytes,7,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Identity      *Identity              `protobuf:"bytes,8,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_internal_models_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{21}
}

func (x *ProtoMessage) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ProtoMessage) GetTimeUs() int64 {
	if x != nil {
		return x.TimeUs
	}
	return 0
}

func (x *ProtoMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProtoMessage) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *ProtoMessage) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ProtoMessage) GetFinSentiment() string {
	if x != nil && x.FinSentiment != nil {
		return *x.FinSentiment
	}
	return ""
}

func (x *ProtoMessage) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ProtoMessage) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_internal_models_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_internal_models_message_proto_rawDescGZIP(), []int{22}
}

func (x *Account) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Account) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Account) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Account) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

var File_internal_models_message_proto protoreflect.FileDescriptor

const file_internal_models_message_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/models/message.proto\x12$stockseer.ai.blueksy.firehose.models\"o\n" +
	"\x05Label\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12C\n" +
	"\x06values\x18\x02 \x03(\v2+.stockseer.ai.blueksy.firehose.models.ValueR\x06valuesB\a\n" +
	"\x05_type\"<\n" +
	"\x05Value\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03valB\a\n" +
	"\x05_type\"\xa2\x01\n" +
	"\x06Entity\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12F\n" +
	"\x05index\x18\x02 \x01(\v2+.stockseer.ai.blueksy.firehose.models.IndexH\x01R\x05index\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x02R\x05value\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_indexB\b\n" +
	"\x06_value\"Z\n" +
	"\bIdentity\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\"\xc7\x01\n" +
	"\x05Facet\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12I\n" +
	"\bfeatures\x18\x02 \x03(\v2-.stockseer.ai.blueksy.firehose.models.FeatureR\bfeatures\x12F\n" +
	"\x05index\x18\x03 \x01(\v2+.stockseer.ai.blueksy.firehose.models.IndexH\x01R\x05index\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_index\"\xd7\x01\n" +
	"\aFeature\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12C\n" +
	"\x04link\x18\x02 \x01(\v2*.stockseer.ai.blueksy.firehose.models.LinkH\x01R\x04link\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x03 \x01(\tH\x02R\x03uri\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x04 \x01(\tH\x03R\x03tag\x88\x01\x01\x12\x15\n" +
	"\x03did\x18\x05 \x01(\tH\x04R\x03did\x88\x01\x01B\a\n" +
	"\x05_typeB\a\n" +
	"\x05_linkB\x06\n" +
	"\x04_uriB\x06\n" +
	"\x04_tagB\x06\n" +
	"\x04_did\"\x18\n" +
	"\x04Link\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"\xa8\x01\n" +
	"\x05Index\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"byte_start\x18\x02 \x01(\x05R\tbyteStart\x12\x19\n" +
	"\bbyte_end\x18\x03 \x01(\x05R\abyteEnd\x12\x15\n" +
	"\x03end\x18\x04 \x01(\x05H\x01R\x03end\x88\x01\x01\x12\x19\n" +
	"\x05start\x18\x05 \x01(\x05H\x02R\x05start\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_endB\b\n" +
	"\x06_start\"\xd9\x06\n" +
	"\x05Embed\x12\x13\n" +
	"\x04type\x18\x01 \x01(\tR\x05$type\x12H\n" +
	"\x06images\x18\x02 \x03(\v20.stockseer.ai.blueksy.firehose.models.EmbedImageR\x06images\x12T\n" +
	"\bexternal\x18\x03 \x01(\v23.stockseer.ai.blueksy.firehose.models.EmbedExternalH\x00R\bexternal\x88\x01\x01\x12K\n" +
	"\x05media\x18\x04 \x01(\v20.stockseer.ai.blueksy.firehose.models.EmbedMediaH\x01R\x05media\x88\x01\x01\x12K\n" +
	"\x05video\x18\x05 \x01(\v20.stockseer.ai.blueksy.firehose.models.EmbedVideoH\x02R\x05video\x88\x01\x01\x12Y\n" +
	"\faspect_ratio\x18\x06 \x01(\v21.stockseer.ai.blueksy.firehose.models.AspectRatioH\x03R\vaspectRatio\x88\x01\x01\x12N\n" +
	"\x06record\x18\a \x01(\v21.stockseer.ai.blueksy.firehose.models.EmbedRecordH\x04R\x06record\x88\x01\x01\x12\x15\n" +
	"\x03alt\x18\b \x01(\tH\x05R\x03alt\x88\x01\x01\x12\x1d\n" +
	"\aalttext\x18\t \x01(\tH\x06R\aalttext\x88\x01\x01\x12\x1f\n" +
	"\bcaptions\x18\n" +
	" \x01(\tH\aR\bcaptions\x88\x01\x01\x12I\n" +
	"\x04data\x18\v \x03(\v25.stockseer.ai.blueksy.firehose.models.Embed.DataEntryR\x04data\x12\x15\n" +
	"\x03uri\x18\f \x01(\tH\bR\x03uri\x88\x01\x01\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_externalB\b\n" +
	"\x06_mediaB\b\n" +
	"\x06_videoB\x0f\n" +
	"\r_aspect_ratioB\t\n" +
	"\a_recordB\x06\n" +
	"\x04_altB\n" +
	"\n" +
	"\b_alttextB\v\n" +
	"\t_captionsB\x06\n" +
	"\x04_uri\"\xbf\x01\n" +
	"\n" +
	"EmbedVideo\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12<\n" +
	"\x03ref\x18\x02 \x01(\v2*.stockseer.ai.blueksy.firehose.models.BlobR\x03ref\x12 \n" +
	"\tmime_type\x18\x03 \x01(\tH\x01R\bmimeType\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x04 \x01(\x05H\x02R\x04size\x88\x01\x01B\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_mime_typeB\a\n" +
	"\x05_size\"\xc4\x01\n" +
	"\vEmbedRecord\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x15\n" +
	"\x03cid\x18\x02 \x01(\tH\x01R\x03cid\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x03 \x01(\tH\x02R\x03uri\x88\x01\x01\x12I\n" +
	"\x06record\x18\x04 \x01(\v2,.stockseer.ai.blueksy.firehose.models.RecordH\x03R\x06record\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_cidB\x06\n" +
	"\x04_uriB\t\n" +
	"\a_record\"\xb9\x03\n" +
	"\n" +
	"EmbedMedia\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12T\n" +
	"\bexternal\x18\x02 \x01(\v23.stockseer.ai.blueksy.firehose.models.EmbedExternalH\x01R\bexternal\x88\x01\x01\x12C\n" +
	"\x06images\x18\x03 \x03(\v2+.stockseer.ai.blueksy.firehose.models.ImageR\x06images\x12Y\n" +
	"\faspect_ratio\x18\x04 \x01(\v21.stockseer.ai.blueksy.firehose.models.AspectRatioH\x02R\vaspectRatio\x88\x01\x01\x12K\n" +
	"\x05video\x18\x05 \x01(\v20.stockseer.ai.blueksy.firehose.models.EmbedVideoH\x03R\x05video\x88\x01\x01\x12\x15\n" +
	"\x03alt\x18\x06 \x01(\tH\x04R\x03alt\x88\x01\x01B\a\n" +
	"\x05_typeB\v\n" +
	"\t_externalB\x0f\n" +
	"\r_aspect_ratioB\b\n" +
	"\x06_videoB\x06\n" +
	"\x04_alt\"\xff\x01\n" +
	"\rEmbedExternal\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12F\n" +
	"\x05thumb\x18\x03 \x01(\v2+.stockseer.ai.blueksy.firehose.models.ImageH\x02R\x05thumb\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x03R\x05title\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x05 \x01(\tH\x04R\x03uri\x88\x01\x01B\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_thumbB\b\n" +
	"\x06_titleB\x06\n" +
	"\x04_uri\"\xc3\x03\n" +
	"\n" +
	"EmbedImage\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x15\n" +
	"\x03alt\x18\x02 \x01(\tH\x01R\x03alt\x88\x01\x01\x12F\n" +
	"\x05image\x18\x03 \x01(\v2+.stockseer.ai.blueksy.firehose.models.ImageH\x02R\x05image\x88\x01\x01\x12Y\n" +
	"\faspect_ratio\x18\x04 \x01(\v21.stockseer.ai.blueksy.firehose.models.AspectRatioH\x03R\vaspectRatio\x88\x01\x01\x12\x1f\n" +
	"\bcaptions\x18\x05 \x01(\tH\x04R\bcaptions\x88\x01\x01\x12N\n" +
	"\x04data\x18\x06 \x03(\v2:.stockseer.ai.blueksy.firehose.models.EmbedImage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_altB\b\n" +
	"\x06_imageB\x0f\n" +
	"\r_aspect_ratioB\v\n" +
	"\t_captions\"^\n" +
	"\vAspectRatio\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05widthB\a\n" +
	"\x05_type\"\xc3\x03\n" +
	"\x05Image\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12A\n" +
	"\x03ref\x18\x02 \x01(\v2*.stockseer.ai.blueksy.firehose.models.BlobH\x01R\x03ref\x88\x01\x01\x12 \n" +
	"\tmime_type\x18\x03 \x01(\tH\x02R\bmimeType\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x04 \x01(\x05H\x03R\x04size\x88\x01\x01\x12Y\n" +
	"\faspect_ratio\x18\x05 \x01(\v21.stockseer.ai.blueksy.firehose.models.AspectRatioH\x04R\vaspectRatio\x88\x01\x01\x12\x15\n" +
	"\x03alt\x18\x06 \x01(\tH\x05R\x03alt\x88\x01\x01\x12F\n" +
	"\x05image\x18\a \x01(\v2+.stockseer.ai.blueksy.firehose.models.ImageH\x06R\x05image\x88\x01\x01\x12\x15\n" +
	"\x03cid\x18\b \x01(\tH\aR\x03cid\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_refB\f\n" +
	"\n" +
	"_mime_typeB\a\n" +
	"\x05_sizeB\x0f\n" +
	"\r_aspect_ratioB\x06\n" +
	"\x04_altB\b\n" +
	"\x06_imageB\x06\n" +
	"\x04_cid\")\n" +
	"\x04Blob\x12\x18\n" +
	"\x04link\x18\x01 \x01(\tH\x00R\x05$link\x88\x01\x01B\a\n" +
	"\x05_link\"\xc6\x02\n" +
	"\x03Ref\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12\x15\n" +
	"\x03cid\x18\x02 \x01(\tH\x01R\x03cid\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x03 \x01(\tH\x02R\x03uri\x88\x01\x01\x12\x18\n" +
	"\x04link\x18\x04 \x01(\tH\x03R\x05$link\x88\x01\x01\x12\x15\n" +
	"\x03ref\x18\x05 \x01(\tH\x04R\x03ref\x88\x01\x01\x120\n" +
	"\x11validation_status\x18\x06 \x01(\tH\x05R\x10validationStatus\x88\x01\x01\x12I\n" +
	"\x06commit\x18\a \x01(\v2,.stockseer.ai.blueksy.firehose.models.CommitH\x06R\x06commit\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_cidB\x06\n" +
	"\x04_uriB\a\n" +
	"\x05_linkB\x06\n" +
	"\x04_refB\x14\n" +
	"\x12_validation_statusB\t\n" +
	"\a_commit\"\xac\x01\n" +
	"\x05Reply\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x05$type\x88\x01\x01\x12A\n" +
	"\x06parent\x18\x02 \x01(\v2).stockseer.ai.blueksy.firehose.models.RefR\x06parent\x12=\n" +
	"\x04root\x18\x03 \x01(\v2).stockseer.ai.blueksy.firehose.models.RefR\x04rootB\a\n" +
	"\x05_type\"\x90\t\n" +
	"\x06Record\x12\x13\n" +
	"\x04type\x18\x01 \x01(\tR\x05$type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05langs\x18\x03 \x03(\tR\x05langs\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12F\n" +
	"\x05embed\x18\x05 \x01(\v2+.stockseer.ai.blueksy.firehose.models.EmbedH\x00R\x05embed\x88\x01\x01\x12F\n" +
	"\x05reply\x18\x06 \x01(\v2+.stockseer.ai.blueksy.firehose.models.ReplyH\x01R\x05reply\x88\x01\x01\x12C\n" +
	"\x06facets\x18\a \x03(\v2+.stockseer.ai.blueksy.firehose.models.FacetR\x06facets\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x15\n" +
	"\x03via\x18\t \x01(\tH\x02R\x03via\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\n" +
	" \x01(\tH\x03R\x05label\x88\x01\x01\x125\n" +
	"\x14bridgy_original_text\x18\v \x01(\tH\x04R\x12bridgyOriginalText\x88\x01\x01\x123\n" +
	"\x13bridgy_original_url\x18\f \x01(\tH\x05R\x11bridgyOriginalUrl\x88\x01\x01\x12\x19\n" +
	"\x05actor\x18\r \x01(\tH\x06R\x05actor\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x0e \x01(\x05H\aR\x04size\x88\x01\x01\x12\x15\n" +
	"\x03cid\x18\x0f \x01(\tH\bR\x03cid\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x10 \x01(\tH\tR\x03uri\x88\x01\x01\x12H\n" +
	"\x06labels\x18\x11 \x01(\v2+.stockseer.ai.blueksy.firehose.models.LabelH\n" +
	"R\x06labels\x88\x01\x01\x12H\n" +
	"\bentities\x18\x12 \x03(\v2,.stockseer.ai.blueksy.firehose.models.EntityR\bentities\x12T\n" +
	"\bexternal\x18\x13 \x01(\v23.stockseer.ai.blueksy.firehose.models.EmbedExternalH\vR\bexternal\x88\x01\x01\x12\x12\n" +
	"\x04lang\x18\x14 \x03(\tR\x04lang\x12\x19\n" +
	"\x05title\x18\x15 \x01(\tH\fR\x05title\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\x16 \x01(\tH\rR\n" +
	"visibility\x88\x01\x01\x12;\n" +
	"\x16space_aoisora_post_via\x18\x17 \x01(\tH\x0eR\x16space.aoisora.post.via\x88\x01\x01B\b\n" +
	"\x06_embedB\b\n" +
	"\x06_replyB\x06\n" +
	"\x04_viaB\b\n" +
	"\x06_labelB\x17\n" +
	"\x15_bridgy_original_textB\x16\n" +
	"\x14_bridgy_original_urlB\b\n" +
	"\x06_actorB\a\n" +
	"\x05_sizeB\x06\n" +
	"\x04_cidB\x06\n" +
	"\x04_uriB\t\n" +
	"\a_labelsB\v\n" +
	"\t_externalB\b\n" +
	"\x06_titleB\r\n" +
	"\v_visibilityB\x19\n" +
	"\x17_space_aoisora_post_via\"\xc4\x01\n" +
	"\x06Commit\x12\x10\n" +
	"\x03rev\x18\x01 \x01(\tR\x03rev\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x04 \x01(\tR\x04rkey\x12D\n" +
	"\x06record\x18\x05 \x01(\v2,.stockseer.ai.blueksy.firehose.models.RecordR\x06record\x12\x10\n" +
	"\x03cid\x18\x06 \x01(\tR\x03cid\"\xa7\x03\n" +
	"\fProtoMessage\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x17\n" +
	"\atime_us\x18\x02 \x01(\x03R\x06timeUs\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12D\n" +
	"\x06commit\x18\x04 \x01(\v2,.stockseer.ai.blueksy.firehose.models.CommitR\x06commit\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12(\n" +
	"\rfin_sentiment\x18\x06 \x01(\tH\x00R\ffinSentiment\x88\x01\x01\x12L\n" +
	"\aaccount\x18\a \x01(\v2-.stockseer.ai.blueksy.firehose.models.AccountH\x01R\aaccount\x88\x01\x01\x12O\n" +
	"\bidentity\x18\b \x01(\v2..stockseer.ai.blueksy.firehose.models.IdentityH\x02R\bidentity\x88\x01\x01B\x10\n" +
	"\x0e_fin_sentimentB\n" +
	"\n" +
	"\b_accountB\v\n" +
	"\t_identity\"\x81\x01\n" +
	"\aAccount\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_statusB/Z-stockseer.ai/blueksy-firehose/internal/modelsb\x06proto3"

var (
	file_internal_models_message_proto_rawDescOnce sync.Once
	file_internal_models_message_proto_rawDescData []byte
)

func file_internal_models_message_proto_rawDescGZIP() []byte {
	file_internal_models_message_proto_rawDescOnce.Do(func() {
		file_internal_models_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_models_message_proto_rawDesc), len(file_internal_models_message_proto_rawDesc)))
	})
	return file_internal_models_message_proto_rawDescData
}

var file_internal_models_message_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_models_message_proto_goTypes = []any{
	(*Label)(nil),         // 0: stockseer.ai.blueksy.firehose.models.Label
	(*Value)(nil),         // 1: stockseer.ai.blueksy.firehose.models.Value
	(*Entity)(nil),        // 2: stockseer.ai.blueksy.firehose.models.Entity
	(*Identity)(nil),      // 3: stockseer.ai.blueksy.firehose.models.Identity
	(*Facet)(nil),         // 4: stockseer.ai.blueksy.firehose.models.Facet
	(*Feature)(nil),       // 5: stockseer.ai.blueksy.firehose.models.Feature
	(*Link)(nil),          // 6: stockseer.ai.blueksy.firehose.models.Link
	(*Index)(nil),         // 7: stockseer.ai.blueksy.firehose.models.Index
	(*Embed)(nil),         // 8: stockseer.ai.blueksy.firehose.models.Embed
	(*EmbedVideo)(nil),    // 9: stockseer.ai.blueksy.firehose.models.EmbedVideo
	(*EmbedRecord)(nil),   // 10: stockseer.ai.blueksy.firehose.models.EmbedRecord
	(*EmbedMedia)(nil),    // 11: stockseer.ai.blueksy.firehose.models.EmbedMedia
	(*EmbedExternal)(nil), // 12: stockseer.ai.blueksy.firehose.models.EmbedExternal
	(*EmbedImage)(nil),    // 13: stockseer.ai.blueksy.firehose.models.EmbedImage
	(*AspectRatio)(nil),   // 14: stockseer.ai.blueksy.firehose.models.AspectRatio
	(*Image)(nil),         // 15: stockseer.ai.blueksy.firehose.models.Image
	(*Blob)(nil),          // 16: stockseer.ai.blueksy.firehose.models.Blob
	(*Ref)(nil),           // 17: stockseer.ai.blueksy.firehose.models.Ref
	(*Reply)(nil),         // 18: stockseer.ai.blueksy.firehose.models.Reply
	(*Record)(nil),        // 19: stockseer.ai.blueksy.firehose.models.Record
	(*Commit)(nil),        // 20: stockseer.ai.blueksy.firehose.models.Commit
	(*ProtoMessage)(nil),  // 21: stockseer.ai.blueksy.firehose.models.ProtoMessage
	(*Account)(nil),       // 22: stockseer.ai.blueksy.firehose.models.Account
	nil,                   // 23: stockseer.ai.blueksy.firehose.models.Embed.DataEntry
	nil,                   // 24: stockseer.ai.blueksy.firehose.models.EmbedImage.DataEntry
}
var file_internal_models_message_proto_depIdxs = []int32{
	1,  // 0: stockseer.ai.blueksy.firehose.models.Label.values:type_name -> stockseer.ai.blueksy.firehose.models.Value
	7,  // 1: stockseer.ai.blueksy.firehose.models.Entity.index:type_name -> stockseer.ai.blueksy.firehose.models.Index
	5,  // 2: stockseer.ai.blueksy.firehose.models.Facet.features:type_name -> stockseer.ai.blueksy.firehose.models.Feature
	7,  // 3: stockseer.ai.blueksy.firehose.models.Facet.index:type_name -> stockseer.ai.blueksy.firehose.models.Index
	6,  // 4: stockseer.ai.blueksy.firehose.models.Feature.link:type_name -> stockseer.ai.blueksy.firehose.models.Link
	13, // 5: stockseer.ai.blueksy.firehose.models.Embed.images:type_name -> stockseer.ai.blueksy.firehose.models.EmbedImage
	12, // 6: stockseer.ai.blueksy.firehose.models.Embed.external:type_name -> stockseer.ai.blueksy.firehose.models.EmbedExternal
	11, // 7: stockseer.ai.blueksy.firehose.models.Embed.media:type_name -> stockseer.ai.blueksy.firehose.models.EmbedMedia
	9,  // 8: stockseer.ai.blueksy.firehose.models.Embed.video:type_name -> stockseer.ai.blueksy.firehose.models.EmbedVideo
	14, // 9: stockseer.ai.blueksy.firehose.models.Embed.aspect_ratio:type_name -> stockseer.ai.blueksy.firehose.models.AspectRatio
	10, // 10: stockseer.ai.blueksy.firehose.models.Embed.record:type_name -> stockseer.ai.blueksy.firehose.models.EmbedRecord
	23, // 11: stockseer.ai.blueksy.firehose.models.Embed.data:type_name -> stockseer.ai.blueksy.firehose.models.Embed.DataEntry
	16, // 12: stockseer.ai.blueksy.firehose.models.EmbedVideo.ref:type_name -> stockseer.ai.blueksy.firehose.models.Blob
	19, // 13: stockseer.ai.blueksy.firehose.models.EmbedRecord.record:type_name -> stockseer.ai.blueksy.firehose.models.Record
	12, // 14: stockseer.ai.blueksy.firehose.models.EmbedMedia.external:type_name -> stockseer.ai.blueksy.firehose.models.EmbedExternal
	15, // 15: stockseer.ai.blueksy.firehose.models.EmbedMedia.images:type_name -> stockseer.ai.blueksy.firehose.models.Image
	14, // 16: stockseer.ai.blueksy.firehose.models.EmbedMedia.aspect_ratio:type_name -> stockseer.ai.blueksy.firehose.models.AspectRatio
	9,  // 17: stockseer.ai.blueksy.firehose.models.EmbedMedia.video:type_name -> stockseer.ai.blueksy.firehose.models.EmbedVideo
	15, // 18: stockseer.ai.blueksy.firehose.models.EmbedExternal.thumb:type_name -> stockseer.ai.blueksy.firehose.models.Image
	15, // 19: stockseer.ai.blueksy.firehose.models.EmbedImage.image:type_name -> stockseer.ai.blueksy.firehose.models.Image
	14, // 20: stockseer.ai.blueksy.firehose.models.EmbedImage.aspect_ratio:type_name -> stockseer.ai.blueksy.firehose.models.AspectRatio
	24, // 21: stockseer.ai.blueksy.firehose.models.EmbedImage.data:type_name -> stockseer.ai.blueksy.firehose.models.EmbedImage.DataEntry
	16, // 22: stockseer.ai.blueksy.firehose.models.Image.ref:type_name -> stockseer.ai.blueksy.firehose.models.Blob
	14, // 23: stockseer.ai.blueksy.firehose.models.Image.aspect_ratio:type_name -> stockseer.ai.blueksy.firehose.models.AspectRatio
	15, // 24: stockseer.ai.blueksy.firehose.models.Image.image:type_name -> stockseer.ai.blueksy.firehose.models.Image
	20, // 25: stockseer.ai.blueksy.firehose.models.Ref.commit:type_name -> stockseer.ai.blueksy.firehose.models.Commit
	17, // 26: stockseer.ai.blueksy.firehose.models.Reply.parent:type_name -> stockseer.ai.blueksy.firehose.models.Ref
	17, // 27: stockseer.ai.blueksy.firehose.models.Reply.root:type_name -> stockseer.ai.blueksy.firehose.models.Ref
	8,  // 28: stockseer.ai.blueksy.firehose.models.Record.embed:type_name -> stockseer.ai.blueksy.firehose.models.Embed
	18, // 29: stockseer.ai.blueksy.firehose.models.Record.reply:type_name -> stockseer.ai.blueksy.firehose.models.Reply
	4,  // 30: stockseer.ai.blueksy.firehose.models.Record.facets:type_name -> stockseer.ai.blueksy.firehose.models.Facet
	0,  // 31: stockseer.ai.blueksy.firehose.models.Record.labels:type_name -> stockseer.ai.blueksy.firehose.models.Label
	2,  // 32: stockseer.ai.blueksy.firehose.models.Record.entities:type_name -> stockseer.ai.blueksy.firehose.models.Entity
	12, // 33: stockseer.ai.blueksy.firehose.models.Record.external:type_name -> stockseer.ai.blueksy.firehose.models.EmbedExternal
	19, // 34: stockseer.ai.blueksy.firehose.models.Commit.record:type_name -> stockseer.ai.blueksy.firehose.models.Record
	20, // 35: stockseer.ai.blueksy.firehose.models.ProtoMessage.commit:type_name -> stockseer.ai.blueksy.firehose.models.Commit
	22, // 36: stockseer.ai.blueksy.firehose.models.ProtoMessage.account:type_name -> stockseer.ai.blueksy.firehose.models.Account
	3,  // 37: stockseer.ai.blueksy.firehose.models.ProtoMessage.identity:type_name -> stockseer.ai.blueksy.firehose.models.Identity
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_internal_models_message_proto_init() }
func file_internal_models_message_proto_init() {
	if File_internal_models_message_proto != nil {
		return
	}
	file_internal_models_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[4].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[5].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[7].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[8].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[9].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[10].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[11].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[12].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[13].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[14].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[15].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[16].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[17].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[18].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[19].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[21].OneofWrappers = []any{}
	file_internal_models_message_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_models_message_proto_rawDesc), len(file_internal_models_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_models_message_proto_goTypes,
		DependencyIndexes: file_internal_models_message_proto_depIdxs,
		MessageInfos:      file_internal_models_message_proto_msgTypes,
	}.Build()
	File_internal_models_message_proto = out.File
	file_internal_models_message_proto_goTypes = nil
	file_internal_models_message_proto_depIdxs = nil
}
