apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bluesky-firehose-classifier-server
  name: bluesky-firehose-classifier-server
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: bluesky-firehose-classifier-server
