apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: adminpass
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: mongo-cm0
          name: mongo-cm0
