apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: mqtt
