apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert --profile default
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
        - image: eclipse-mosquitto:latest
          name: mqtt
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/passwd_file
              name: mqtt-cm0
              subPath: passwd_file
            - mountPath: /mosquitto/config/mosquitto.conf
              name: mqtt-cm1
              subPath: mosquitto.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: mosquitto.passwd
                path: passwd_file
            name: mqtt-cm0
          name: mqtt-cm0
        - configMap:
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
            name: mqtt-cm1
          name: mqtt-cm1
